// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"
)

type Querier interface {
	CreateCategory(ctx context.Context, name string) (Category, error)
	CreateOrder(ctx context.Context, arg CreateOrderParams) (Order, error)
	CreateOrderItem(ctx context.Context, arg CreateOrderItemParams) (OrderItem, error)
	CreateProduct(ctx context.Context, arg CreateProductParams) (Product, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	GetProduct(ctx context.Context, id int64) (Product, error)
	GetUser(ctx context.Context, username string) (User, error)
	ListProducts(ctx context.Context, arg ListProductsParams) ([]Product, error)
}

var _ Querier = (*Queries)(nil)
